### PR TITLE
Implemented Pytorch optimization strategies

### PR DESCRIPTION
**Pull request by nik1806**
The PR adds support for 'Local Prune', 'Global Prune', 'Dynamic range quantization', 'Quantization aware training' and 'Pruning + QAT'.

### CODE REVIEW

**Comment by sergiopaniego** [comment]
Could you add a similar table with PyTorch models download links, please?
In addition, the tensorflow folder seems to be out of scope for this PR.

**Comment by nik1806** [comment]
The table with download links are already available. Please see file `Formula1-FollowLine/pytorch/README.md` in last commit https://github.com/JdeRobot/DeepLearningStudio/pull/72/commits/74319fc5868a80b9ba142830c58a51ffbd169a5a

**Comment by sergiopaniego** [comment]
Thanks for pointing out that commit! I missed it. 
 Could you update this branch to the latest main branch commit so the Tensorflow part is updated?

**Comment by nik1806** [comment]
Updated the branch. Ready to merge :)

**Pull request merged**
